services:
  postgres:
    image: postgres:16
    container_name: kubiku-db
    environment:
      POSTGRES_DB: kubiku
      POSTGRES_USER: kubiku
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - kubiku_db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: kubiku-auth
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8082:8080"
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      postgres_keycloak:
        condition: service_healthy

  postgres_keycloak:
    image: postgres:16
    container_name: kubiku-auth-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  kubiku_db_data:
