services:
  postgres:
    image: postgres:16
    container_name: kubiku-db
    environment:
      POSTGRES_DB: kubiku
      POSTGRES_USER: kubiku
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - kubiku_db_data:/var/lib/postgresql/data

volumes:
  kubiku_db_data:
