services:
  - type: web
    name: kubiku-api
    env: docker
    dockerContext: apps/api
    dockerfilePath: apps/api/Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.mddkcrjafjkhxwscbogj
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_FLYWAY_BASELINE_ON_MIGRATE
        value: "true"
      - key: SPRING_FLYWAY_BASELINE_VERSION
        value: "2"
      - key: ALLOWED_ORIGINS
        value: "https://kubiku-premium-realestate-web.vercel.app,http://localhost:3000,http://127.0.0.1:3000"
      - key: SUPABASE_URL
        value: https://mddkcrjafjkhxwscbogj.supabase.co
      - key: SUPABASE_JWT_ISSUER
        value: https://mddkcrjafjkhxwscbogj.supabase.co/auth/v1
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:+UseContainerSupport -Xms128m -Xmx384m -XX:+UseSerialGC"
    healthCheckPath: /actuator/health
